# Generated by Django 5.1.4 on 2025-12-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_session_in_progress_session_paused_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
