# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_session_is_paused_session_paused_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='youtube_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
