# Generated by Django 5.1.4 on 2026-04-05 07:23

import django.db.models.deletion
import session.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_session_youtube_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=session.models.sheet_music_upload_path)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('page_count', models.PositiveSmallIntegerField()),
                ('file_hash', models.CharField(help_text='SHA256 hash of file content', max_length=64)),
                ('last_page_viewed', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_music', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'file_hash'), ('user', 'title')},
            },
        ),
    ]
