# Generated by Django 5.1.4 on 2026-07-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0011_track_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='called_key',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='track',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('mp3', 'MP3'), ('pdf', 'PDF'), ('image', 'Image'), ('none', 'No source yet')], max_length=10),
        ),
    ]
