"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
import dj_database_url

from django_project.storage import r2_storage_options

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_env():
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return

    for raw_line in env_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip("\"'"))


load_local_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "local-development-only-secret-key-change-me-before-deploying-2026",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"
IS_TESTING = "pytest" in sys.modules or "PYTEST_CURRENT_TEST" in os.environ

def split_env_list(name, default=""):
    return [value.strip() for value in os.getenv(name, default).split(",") if value.strip()]


# ALLOWED_HOSTS - restrict to specific domains in production.
# Railway injects the public and private service hostnames at runtime; include
# them so frontend-to-backend proxy requests are not rejected before DRF runs.
ALLOWED_HOSTS = split_env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS += split_env_list("RAILWAY_PUBLIC_DOMAIN")
ALLOWED_HOSTS += split_env_list("RAILWAY_PRIVATE_DOMAIN")
if IS_TESTING:
    ALLOWED_HOSTS.append("testserver")
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # 3rd-party apps
    "rest_framework",
    "corsheaders",
    "rest_framework.authtoken",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "drf_spectacular",

    
    # Local
    "accounts.apps.AccountsConfig",
    "session.apps.SessionConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "django_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ],
        },
    },
]

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)

SITE_ID = 1

# ─── Allauth + email verification (see issue #16) ────────────────────
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[The Shed] "
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_CONFIRM_EMAIL_ON_GET = False  # our POST /verify-and-login/ handles it
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
ACCOUNT_ADAPTER = "accounts.adapter.CustomAccountAdapter"

REST_AUTH = {
    "PASSWORD_RESET_SERIALIZER": "accounts.serializers.FrontendPasswordResetSerializer",
    "OLD_PASSWORD_FIELD_ENABLED": True,
}

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "hello@theshed.app")

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


# SendGrid in prod; console backend (already set above) stays default in dev.
if os.getenv("SENDGRID_API_KEY"):
    EMAIL_BACKEND = "django_project.email_backends.SendGridApiEmailBackend"
    EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
elif EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend":
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.sendgrid.net")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "apikey")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
    EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
    EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))

WSGI_APPLICATION = "django_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use Railway's DATABASE_URL in production, fallback to local for development
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Production: Use Railway's PostgreSQL database
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif os.getenv("USE_DOCKER_DB", "False") == "True":
    # Development: Use local Docker PostgreSQL
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "postgres",
            "USER": "postgres",
            "PASSWORD": "postgres",
            "HOST": "db",
            "PORT": 5432,
        }
    }
else:
    # Local development and test fallback. Production must set DATABASE_URL.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", BASE_DIR / "media"))
TRACK_FILE_MAX_UPLOAD_SIZE = int(os.getenv("TRACK_FILE_MAX_UPLOAD_SIZE", str(50 * 1024 * 1024)))
TAKE_FILE_MAX_UPLOAD_SIZE = int(os.getenv("TAKE_FILE_MAX_UPLOAD_SIZE", str(250 * 1024 * 1024)))
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", str(20 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("FILE_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024)))

# WhiteNoise configuration for serving static files in production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ─── Durable media storage: Cloudflare R2 (optional) ────────────────
# When R2_BUCKET, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, and
# R2_ENDPOINT_URL are all set, uploaded media (tracks, charts, takes) is
# stored in a private R2 bucket via django-storages' S3 backend. With none
# of them set, local MEDIA_ROOT behavior is unchanged (dev + tests).
# See django_project/storage.py and RAILWAY_DEPLOYMENT.md → "Durable media
# storage (Cloudflare R2)".
_R2_STORAGE_OPTIONS = r2_storage_options(os.environ)
USE_R2_MEDIA_STORAGE = _R2_STORAGE_OPTIONS is not None
if USE_R2_MEDIA_STORAGE:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": _R2_STORAGE_OPTIONS,
    }

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.CustomUser"

REST_FRAMEWORK = {  
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",],
        "DEFAULT_AUTHENTICATION_CLASSES":[
            "rest_framework.authentication.SessionAuthentication",
            "accounts.authentication.CookieTokenAuthentication",
        
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_RATES": {
        "auth_login": os.getenv("AUTH_LOGIN_RATE_LIMIT", "10/minute"),
        "auth_register": os.getenv("AUTH_REGISTER_RATE_LIMIT", "5/minute"),
        "auth_password_reset": os.getenv("AUTH_PASSWORD_RESET_RATE_LIMIT", "5/minute"),
        "auth_email_verification": os.getenv("AUTH_EMAIL_VERIFICATION_RATE_LIMIT", "10/minute"),
        "recommendations": os.getenv("OPENAI_RECOMMENDATIONS_RATE_LIMIT", "5/hour"),
    },
}

AUTH_TOKEN_COOKIE_NAME = os.getenv("AUTH_TOKEN_COOKIE_NAME", "practice_auth_token")
AUTH_TOKEN_COOKIE_HTTPONLY = True
AUTH_TOKEN_COOKIE_SAMESITE = "Lax"
AUTH_TOKEN_COOKIE_SECURE = env_bool("AUTH_TOKEN_COOKIE_SECURE", not DEBUG)
AUTH_TOKEN_COOKIE_MAX_AGE = int(
    os.getenv("AUTH_TOKEN_COOKIE_MAX_AGE", str(60 * 60 * 24 * 30))
)
AUTH_TOKEN_COOKIE_PATH = "/"

# CORS Configuration - Allow frontend to make requests to backend
# Get allowed origins from environment variable for production
CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://localhost:8000"
).split(",")

# For development, allow credentials (cookies, auth headers)
CORS_ALLOW_CREDENTIALS = True

# CSRF Configuration - Trust these origins for CSRF tokens
CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:3000"
).split(",")

# Security settings for production
# Railway (and similar PaaS) terminates SSL at the proxy level,
# so we trust the X-Forwarded-Proto header instead of redirecting ourselves.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not IS_TESTING)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


SPECTACULAR_SETTINGS = {
    "TITLE": "Musicians Practice App",
    "DESCRIPTION": "The backend for my musician practice app",
    "VERSION": "1.0.0",
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
